name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-path: tests/build
    steps:
      - uses: actions/checkout@v3
      - name: Install CMake ≥3.30
        run: |
          wget https://apt.kitware.com/kitware-archive.sh
          sudo bash kitware-archive.sh
          sudo apt-get update && sudo apt-get install -y cmake
      - name: Configure & Build
        run: |
          mkdir -p tests/build
          cd tests/build
          cmake .. && cmake --build .
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: tests/build/

  call-tests:
    needs: build
    uses: ./.github/workflows/tests.yml
    with:
      build-path: ${{ needs.build.outputs.build-path }}
